{
 "title": "Fuel metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <img src=\"https://cumulo.pro/images/fuel.png\" alt=\"Logo\" style=\"height: 150px;\"> <!-- Ajusta la altura según sea necesario -->\n    <h2>Fuel Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n</div>\n"
   }
  },
  {
   "title": "Node version",
   "type": "stat",
   "description": "Current version of the Fuel node",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fuel_node_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fuel Chain Height",
   "type": "stat",
   "description": "Indicates the current height of the chain Fuel",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fuel_chain_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fuel Height",
   "type": "stat",
   "description": "Indicates the current height of the Fuel node block",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "fuel_height", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fuel Health",
   "type": "stat",
   "description": "Displays the current health status of the Fuel node, where 1 indicates healthy and 0 indicates unhealthy.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fuel_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block delay",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A-$B", "type": "math" }
   ]
  },
  {
   "title": "Block ID",
   "type": "table",
   "description": "Provides information on the current block number that a particular Fuel node has reached. This value can be used to monitor the node's synchronisation progress with the blockchain and verify that it is in the correct or expected block.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "last_over_time(fuel_block_id[5s])",
     "legendFormat": "{{block_id}}"
    }
   ]
  },
  {
   "title": "Peer IDs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "expr": "fuel_peer_id", "legendFormat": "{{peer_id}}" }
   ]
  }
 ]
}